Portfolio and mobile version- skeleton
kelomo2502/my-portfolio pull request #1
Opened 2022-03-21 17:21 UTC by kelomo2502

**In this first milestone :**

- Set up a new repository and prepare it for development using best practices (e.g. linters)
- Choose a template from Figma and parse to create a user interface
- Build the first 2 sections of the mobile website using the template chosen from figma
- Build the first two sections of the mobile portfolio using flexbox

2022-03-21 18:16 UTC, Whoistolu requested changes
Hi @kelomo2502 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-21 18:16 UTC, Whoistolu commented on .github/workflows/linters.yml
> -      - name: Run a multi-line script
- Kindly note that you are not allowed to alter the `linter` files. There should be no custom changes to `linter` config.

2022-03-21 18:16 UTC, Whoistolu commented on index.html
> +      </nav>
- [ ] [REQUIRED] Kindly note that the container of the navigation bar should be a `header` tag. The `header` tag in HTML is used to define the header for a document or a section as it contains the information related to the title and heading of the related content. The `header` element is intended to usually contain the section's heading. Kindly implement this.

2022-03-21 18:16 UTC, Whoistolu commented on style.css
> +font-family: 'Fira Sans', sans-serif; */
- Kindly remove all unused lines of code in order to have a clean code-base.

2022-03-21 18:16 UTC, Whoistolu commented on index.html
> +                </ul>
- [ ] [REQUIRED] Great job implementing the social icons in an unordered list (ul) and (li) for each icon, however, not all icons seem to be displaying properly. Kindly fix this in order to meet up with the project requirement.
### Your Icons
![Screenshot from 2022-03-21 19-09-54](https://user-images.githubusercontent.com/58692590/159337475-5021cf5c-13f3-428a-b22b-620516192bde.png)

2022-03-21 18:30 UTC, kelomo2502 commented
Thank you for your email.
Will rework and revert back to you.

Gbenga


On Mon, 21 Mar 2022, 7:16 pm Ajise Toluwase, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @kelomo2502 <https://github.com/kelomo2502>
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Required Changes ♻️
>
>    - *Check the inline comments under the review for sections to improve.*
>
> Optional suggestions
>
> Every comment with the [OPTIONAL] prefix is not crucial enough to stop the
> approval of this PR. However, I strongly recommend you to take them into
> account as they can make your code better.
>
> Cheers and Happy coding!
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me @Whoistolu <https://github.com/Whoistolu> in
> your question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In .github/workflows/linters.yml
> <https://github.com/kelomo2502/my-portfolio/pull/1#discussion_r831398445>:
>
> > -# This is a basic workflow to help you get started with Actions
>
> +name: Linters
>
>
>
> -name: CI
>
> +on: pull_request
>
>
>
> -# Controls when the workflow will run
>
> -on:
>
> -  # Triggers the workflow on push or pull request events but only for the main branch
>
> -  push:
>
> -    branches: [ main ]
>
> -  pull_request:
>
> -    branches: [ main ]
>
> +env:
>
> +  FORCE_COLOR: 1
>
>
>
> -  # Allows you to run this workflow manually from the Actions tab
>
> -  workflow_dispatch:
>
> -
>
> -# A workflow run is made up of one or more jobs that can run sequentially or in parallel
>
>  jobs:
>
> -  # This workflow contains a single job called "build"
>
> -  build:
>
> -    # The type of runner that the job will run on
>
> -    runs-on: ubuntu-latest
>
> -
>
> -    # Steps represent a sequence of tasks that will be executed as part of the job
>
> +  lighthouse:
>
> +    name: Lighthouse
>
> +    runs-on: ubuntu-18.04
>
>      steps:
>
> -      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
>
>        - uses: ***@***.***
>
> -
>
> -      # Runs a single command using the runners shell
>
> -      - name: Run a one-line script
>
> -        run: echo Hello, world!
>
> -
>
> -      # Runs a set of commands using the runners shell
>
> -      - name: Run a multi-line script
>
>
>
>    - Kindly note that you are not allowed to alter the linter files.
>    There should be no custom changes to linter config.
>
> ------------------------------
>
> In index.html
> <https://github.com/kelomo2502/my-portfolio/pull/1#discussion_r831401515>:
>
> > +      <nav class="nav-bar">
>
> +            <a href="#">Gbenga</a>
>
> +            <img class="logo" src="./images/hamburger/Union.png" alt="drop-menu">
>
> +      </nav>
>
>
>
>    - [REQUIRED] Kindly note that the container of the navigation bar
>    should be a header tag. The header tag in HTML is used to define the
>    header for a document or a section as it contains the information related
>    to the title and heading of the related content. The header element is
>    intended to usually contain the section's heading. Kindly implement this.
>
> ------------------------------
>
> In style.css
> <https://github.com/kelomo2502/my-portfolio/pull/1#discussion_r831403335>:
>
> > +/* CSS rules to specify families
>
> +
>
> +font-family: 'Fira Sans', sans-serif; */
>
>
>
>    - Kindly remove all unused lines of code in order to have a clean
>    code-base.
>
> ------------------------------
>
> In index.html
> <https://github.com/kelomo2502/my-portfolio/pull/1#discussion_r831408322>:
>
> > +                <ul class="social-icons">
>
> +                   <li class="three"><img src="./images/git.png" alt="vector3"></li>
>
> +                   <li class="four"><img src="./images/group-linkedin.png" alt="vector4"></li>
>
> +                   <li class="six"><img src="./images/vector5.png" alt="vector4"></li>
>
> +                   <li class="seven"><img src="./images/vector6.png" alt="vector6"></li>
>
> +                   <li class="eight"><img src="./images/vector7.png" alt="vector6"></li>
>
> +                </ul>
>
>
>
>    - [REQUIRED] Great job implementing the social icons in an unordered
>    list (ul) and (li) for each icon, however, not all icons seem to be
>    displaying properly. Kindly fix this in order to meet up with the project
>    requirement.
>
> Your Icons
>
> [image: Screenshot from 2022-03-21 19-09-54]
> <https://user-images.githubusercontent.com/58692590/159337475-5021cf5c-13f3-428a-b22b-620516192bde.png>
> ------------------------------
>
> In index.html
> <https://github.com/kelomo2502/my-portfolio/pull/1#discussion_r831410785>:
>
> > +  <meta charset="UTF-8">
>
> +  <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> +  <title>gbenga's-portfolio</title>
>
> +  <link rel="preconnect" href="https://fonts.googleapis.com">
>
> +<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
>
> +<link ***@***.***;700&display=swap" rel="stylesheet">
>
> +
>
> +  <link rel="stylesheet" href="style.css">
>
> +</head>
>
> +<body>
>
> +      <nav class="nav-bar">
>
> +            <a href="#">Gbenga</a>
>
> +            <img class="logo" src="./images/hamburger/Union.png" alt="drop-menu">
>
> +      </nav>
>
> +      <section class="headline">
>
>
>
>    - [REQUIRED] Kindly remove the excess white space at the bottom of the
>    screen and the one on the right so your project can look like the template
>    provided.
>
> Your design
>
> [image: Screenshot from 2022-03-21 19-13-28]
> <https://user-images.githubusercontent.com/58692590/159337973-e08b1c88-04c6-41da-be0a-4a70e54d3311.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kelomo2502/my-portfolio/pull/1#pullrequestreview-916155772>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWGFPKGEPOFYXWCC37ZSKMDVBC4JPANCNFSM5RIMCWPQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-22 10:19 UTC, ShoiraTa requested changes
STATUS: CHANGES REQUIRED 🟡 
----
Hi @kelomo2502,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are some issues that you still need to work on to go to the next project but you are almost there!

![woohoo-youre-almost](https://user-images.githubusercontent.com/77038610/154921145-1f7bb8f6-c843-4ba5-a534-6b840c600558.jpeg)


 ## Required Changes  :recycle: 

_Check the comments under the review._ 

## Optional suggestions

_Check the comments under the review._ 

 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 10:19 UTC, ShoiraTa commented on style.css
> +font-family: 'Fira Sans', sans-serif; */
- [ ] As the previous reviewer requested, please remove all unused lines of code in order to have a clean code-base.

2022-03-22 10:19 UTC, ShoiraTa commented on index.html
> +                </ul>
- [ ] As the previous reviewer requested, please make sure that all icons are being rendered properly as provided in Figma design: 

Your design  | Figma design
------------- | -------------
<img width="298" alt="Screenshot 2022-03-22 at 14 05 11" src="https://user-images.githubusercontent.com/77038610/159456350-14f4074c-291e-4be1-8693-ea091d744c5e.png"> | <img width="295" alt="Screenshot 2022-03-22 at 14 06 15" src="https://user-images.githubusercontent.com/77038610/159456575-155d9f98-a865-463f-8af6-a54035f1724d.png">

Eg.: There is a typo in `/images/vector6.png` it should be `/images/Vector6.png`

- [ ] Please set the color of icons to `#DBD8D7` curretly only Linkedin icon is of similar color.

2022-03-22 10:19 UTC, ShoiraTa commented on index.html
> +      <section class="headline">
- [ ] As the previous reviewer requested, kindly remove the excess white space at the bottom of the screen and the one on the right so your project can look like the template provided. Currenlty, there is white space if the screen size gets smaller than `392px`

Your design  | Figma design
------------- | -------------
<img width="382" alt="Screenshot 2022-03-22 at 14 12 31" src="https://user-images.githubusercontent.com/77038610/159457665-dea3bdb4-3acb-46f4-bd06-52b4e944df0e.png">  | <img width="301" alt="Screenshot 2022-03-22 at 14 13 14" src="https://user-images.githubusercontent.com/77038610/159457798-839c5179-2649-490a-b130-d64c8d6e116e.png">

- [  ]OPTIONAL:  Please make sure to decrease the font size as provided in Figma to `56px`

- [ ] OPTIONAL:  Please make sure to have the same font family as in Figma, which is 'Poppins'

- [ ] After making all the changes, please make sure that your page looks same as the design in Figma  🙏🏻

2022-03-22 10:19 UTC, ShoiraTa commented on index.html
> +
- [ ] OPTIONAL:  This image is supposed to be a background image. Therefore, please upload it from css as a background image

2022-03-22 10:19 UTC, ShoiraTa commented on index.html
> +      <section class="headline">
- [ ] OPTIONAL:  Headline section had to be aligned with `flexbox`. Please try to use `flexbox` to align this section

2022-03-23 13:17 UTC, kelomo2502 commented
![Screenshot (9)](https://user-images.githubusercontent.com/93083560/159707561-86927130-1131-4ff7-ad17-916d00b30a7e.png)

- All Icons display correctly
- Icons color are set to figma template
- Extra Whites spaces removed
- Background-Image uploaded from style.css

2022-03-23 14:12 UTC, gemmen29 approved these changes
Hi @kelomo2502, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions:
- [ ] Kindly give the branch a meaningful name, not `request-review` like the name of the project `setup-and-mobile-version-skeleton`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 14:34 UTC, merged